# Generated by Django 5.2.4 on 2025-07-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedditPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subreddit', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('score', models.IntegerField()),
                ('comments', models.IntegerField()),
                ('post_time', models.DateTimeField()),
                ('post_content', models.TextField(blank=True, null=True)),
                ('url', models.URLField(max_length=500)),
                ('temp_field', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'ordering': ['-post_time'],
                'unique_together': {('subreddit', 'title', 'post_time')},
            },
        ),
    ]
